services:
  # BUILDER
  builder:
    container_name: vaccinex-builder
    build:
      context: .
      dockerfile: docker/builder/Dockerfile
    volumes:
      - ../../maven-cache:/root/.m2
      - ./data/spring-boot-data:/temp/build-output
    networks:
      - vaccine-network

  # RUNNER
  runner:
    container_name: vaccinex-runner
    build:
      context: .
      dockerfile: docker/runner/Dockerfile
    depends_on:
      builder:
        condition: service_completed_successfully
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://mssql:1433;databaseName=vaccine;user=sa;password=Admin@12345;encrypt=true;trustServerCertificate=true
    ports:
      - "1111:8080"
    volumes:
      - ./data/spring-boot-data:/temp/build-output
    restart: no
    networks:
      - vaccine-network
      - mssql-network

  # ZOOKEEPER
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - vaccine-network

  # KAFKA
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - vaccine-network

networks:
  mssql-network:
    external: true
  vaccine-network:
    name: vaccine-network
    driver: bridge